import { prisma } from "@/lib/prisma";
import { NextRequest, NextResponse } from "next/server";

export async function GET(request:NextRequest) {
    
    const testimonial = await prisma.testimonial.findMany({})
    return NextResponse.json(testimonial, { status: 201 });
}

export async function POST(request: NextRequest) {
  try {
    const body = await request.json();
    const { id, name, role, text, rating } = body;

    // Basic validation
    if (!name || !text) {
      return NextResponse.json(
        { error: "Missing required fields" },
        { status: 400 }
      );
    }

    const testimonial = await prisma.testimonial.create({
      data: {
        id, // Note: Usually IDs are auto-generated by the DB
        name,
        role,
        text,
        rating,
      },
    });

    return NextResponse.json(testimonial, { status: 201 });
  } catch (error) {
    console.error("Request error", error);
    return NextResponse.json(
      { error: "Error creating testimonial" },
      { status: 500 }
    );
  }
}